### ISSUE TITLE
[1.21] [NeoForge] Crafting on a stick won't equip in curios

### ISSUE THREAD

**Issue by MersoNocte** [JDKDigital/Adorned#14]
NeoForge 21.1.80
Minecraft 1.21.1
curios-neoforge-9.1.4+1.21.0

Crafting on a stick won't equip in the "crafting on a stick" curios slot. It will only equip in a Charms slot.

**Comment by JaisDK** [comment]
Report it to them. This is an API and if they use it wrong I can’t help
