### ISSUE TITLE
[Bug]: Game crash with -Dmixin.debug.countInjections=true

### ISSUE THREAD

**Issue by Lolothepro** [JDKDigital/Adorned#3]
### Minecraft Version

1.20.6

### What happened?

Game crash with -Dmixin.debug.countInjections=true

### How do you trigger this bug?

Start the game with -Dmixin.debug.countInjections=true

### Loader

NeoForge

### Loader Version

21.0.76-beta

### Mod Version

Adorned API 9.0.2+1.21.0

### Relevant Log Outputs

https://mclo.gs/6dySGj6

**Comment by JaisDK** [comment]
That's a very hand param, thanks for the report.
