### ISSUE TITLE
[Bug]: Status UI cover the Curio menu

### ISSUE THREAD

**Issue by ffuentesm** [JDKDigital/Adorned#4]
### Minecraft Version

1.21.1

### What happened?

![image](https://github.com/user-attachments/assets/0dad9bee-0224-46d9-9089-aabf1e16977d)
I had the same problem with Accessories a while ago. 
I am currently using EMI to change the Status icons from the right to the left side, but many other mods do the same thing. 

The option I recommend is to have the status UI to be off when the curio slots are in display. 

### Loader

NeoForge

### Loader Version

21.1.1

### Mod Version

curios-neoforge-9.0.5+1.21.0

**Comment by JaisDK** [comment]
fixed
