### ISSUE TITLE
[Bug]: Curios item with binding curse can be taken off even if the player is not in creative mode

### ISSUE THREAD

**Issue by Amotassic** [JDKDigital/Adorned#8]
### Minecraft Version
1.21.1

### Loader
NeoForge

### Loader Version
21.1.4

### Mod Version
curios-neoforge-9.0.5+1.21.0 and curios-neoforge-9.1.2+1.21.0

**Comment by JaisDK** [comment]
As far as I can tell from looking at the source for 1.20.1 this has never been the case so I don't know yet if I should add it.

**Comment by gazinga1992** [comment]
I'm having this same issue and the curse of binding works back in curios 1.20.1. It also works with the other curios fork for 1.21 when I tried it.

**Comment by JaisDK** [comment]
got it sorted in latest release
